apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: guest-namespace-step24
  name: guest-deployment-2
  labels:
    part-of: guest-part
    component: guest-backend-server
    name: guest
    version: 2.0.0
    managed-by: kubectl
spec:
  selector:
    matchLabels:
      part-of: guest-part
      component: guest-backend-server
      name: guest
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        part-of: guest-part
        component: guest-backend-server
        name: guest
        version: 2.0.0
        blue-green-no: "2"
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-master
      containers:
        - name: guest-container-2
          image: academyitwill/guest:v2
          imagePullPolicy: Always
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: mysql-prod-group 
          ports:
            - containerPort: 8080
              name: http
